# This file was generated by GoReleaser. DO NOT EDIT.
cask "epm" do
  name "epm"
  desc "Terminal dashboard for Elasticsearch cluster performance monitoring"
  homepage "https://github.com/jtsunne/epm-go"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "epm"

  on_macos do
    on_intel do
      url "https://github.com/jtsunne/epm-go/releases/download/v#{version}/epm_#{version}_darwin_amd64.tar.gz"
      sha256 "3f6dd326441dab371fbb855fdc594cf5fbe131ed33cfdae8b3c8b82b26b7e633"
    end
    on_arm do
      url "https://github.com/jtsunne/epm-go/releases/download/v#{version}/epm_#{version}_darwin_arm64.tar.gz"
      sha256 "cb77f3bd45c803e4fd6aa0c81cae42c6252e5b6aff7ef37e5e6f4e51b4727363"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jtsunne/epm-go/releases/download/v#{version}/epm_#{version}_linux_amd64.tar.gz"
      sha256 "510ae89fc3f42bb2d9c3da05405e065632b6f8d473542270ce86d65140d98771"
    end
    on_arm do
      url "https://github.com/jtsunne/epm-go/releases/download/v#{version}/epm_#{version}_linux_arm64.tar.gz"
      sha256 "83e10f9cec7e32b656e94718f3b29b0941858f1b77ed853fbff3ee7d0c7d031c"
    end
  end

  # No zap stanza required
end
