# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epm < Formula
  desc "Terminal dashboard for Elasticsearch cluster performance monitoring"
  homepage "https://github.com/jtsunne/epm-go"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.1.1/epm_0.1.1_darwin_amd64.tar.gz"
      sha256 "24509980bd46fb121349c4fa9ee8eb7d1f5f8afd5fc375bbe209c8f2302bbb34"

      define_method(:install) do
        bin.install "epm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.1.1/epm_0.1.1_darwin_arm64.tar.gz"
      sha256 "81d5f8119bdba801774b80d487c82edad8b1c087eed30fe6ae590fc1b09cd4ba"

      define_method(:install) do
        bin.install "epm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.1.1/epm_0.1.1_linux_amd64.tar.gz"
      sha256 "59d2a17ed8b014e5fef8ae348e63e6724171ba866d1a4700070bcc9b7dc49981"
      define_method(:install) do
        bin.install "epm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.1.1/epm_0.1.1_linux_arm64.tar.gz"
      sha256 "b1e78d57dde1896ab457267add9f20a492321f58a1c8f41308c054f68573dcfe"
      define_method(:install) do
        bin.install "epm"
      end
    end
  end

  test do
    system "#{bin}/epm", "--version"
  end
end
