# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epm < Formula
  desc "Terminal dashboard for Elasticsearch cluster performance monitoring"
  homepage "https://github.com/jtsunne/epm-go"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.2.0/epm_0.2.0_darwin_amd64.tar.gz"
      sha256 "069232d54939f905b514ccdeef63eca86cc345b113ea063c8016a2f72f83efe4"

      define_method(:install) do
        bin.install "epm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.2.0/epm_0.2.0_darwin_arm64.tar.gz"
      sha256 "1e08d750802a6d634833c4308aea787dbfd151ce1302e104d04eda8a0d6be56b"

      define_method(:install) do
        bin.install "epm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.2.0/epm_0.2.0_linux_amd64.tar.gz"
      sha256 "2e2d3927db197ee3d66c13ec67e7345b47b87507e8a6db31383164425ee23582"
      define_method(:install) do
        bin.install "epm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.2.0/epm_0.2.0_linux_arm64.tar.gz"
      sha256 "50eb4a5352521d284b655bbfb5bcea862bdf2fc0bdbc43cb1e61b892ad3905e1"
      define_method(:install) do
        bin.install "epm"
      end
    end
  end

  test do
    system "#{bin}/epm", "--version"
  end
end
