# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epm < Formula
  desc "Terminal dashboard for Elasticsearch cluster performance monitoring"
  homepage "https://github.com/jtsunne/epm-go"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.3.0/epm_0.3.0_darwin_amd64.tar.gz"
      sha256 "06382c1b83d597d2a14e5bf60b6e1e88b5c4cbca838b36ff983c3c2566c71a3b"

      define_method(:install) do
        bin.install "epm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.3.0/epm_0.3.0_darwin_arm64.tar.gz"
      sha256 "2931c4d3721e3ce914425751f60e18f67a7be02c449cd642419cfe55b329ae5f"

      define_method(:install) do
        bin.install "epm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.3.0/epm_0.3.0_linux_amd64.tar.gz"
      sha256 "600fb842c9d6dad3568625994731fca54cd83831b4f90d8563613d31f895968e"
      define_method(:install) do
        bin.install "epm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtsunne/epm-go/releases/download/v0.3.0/epm_0.3.0_linux_arm64.tar.gz"
      sha256 "c9c025331b2bb06a39d260a394d1c911def9332e126f09f8cc4287a4bba1172d"
      define_method(:install) do
        bin.install "epm"
      end
    end
  end

  test do
    system "#{bin}/epm", "--version"
  end
end
